services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: promotions_db  # Correct database name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: